// lib/data.ts
import { Product, Ingredient, Tool } from './types';

export const defaultIngredients: Ingredient[] = [
	{ id: '1', name: 'Harina', price: 25, unit: 'kg', amount: 1, minAmount: 0.8 },
	{ id: '2', name: 'Azúcar', price: 18, unit: 'kg', amount: 1, minAmount: 0.2 },
	{
		id: '3',
		name: 'Mantequilla',
		price: 120,
		unit: 'kg',
		amount: 1,
		minAmount: 0.15,
	},
	{
		id: '4',
		name: 'Canela',
		price: 200,
		unit: 'kg',
		amount: 1,
		minAmount: 0.03,
	},
	{
		id: '5',
		name: 'Levadura',
		price: 45,
		unit: 'kg',
		amount: 1,
		minAmount: 0.03,
	},
	{
		id: '6',
		name: 'Huevos',
		price: 45,
		unit: 'docena',
		amount: 1,
		minAmount: 0.3,
	},
	{
		id: '7',
		name: 'Leche',
		price: 25,
		unit: 'litro',
		amount: 1,
		minAmount: 0.3,
	},
	{
		id: '8',
		name: 'Crema para glaseado',
		price: 85,
		unit: 'kg',
		amount: 1,
		minAmount: 0.1,
	},
	{
		id: '9',
		name: 'Chocolate',
		price: 150,
		unit: 'kg',
		amount: 1,
		minAmount: 0.1,
	},
	{
		id: '10',
		name: 'Fresas',
		price: 80,
		unit: 'kg',
		amount: 1,
		minAmount: 0.2,
	},
	{
		id: '11',
		name: 'Arándanos',
		price: 120,
		unit: 'kg',
		amount: 1,
		minAmount: 0.2,
	},
	{
		id: '12',
		name: 'Caramelo',
		price: 95,
		unit: 'kg',
		amount: 1,
		minAmount: 0.1,
	},
	{
		id: '13',
		name: 'Queso crema',
		price: 110,
		unit: 'kg',
		amount: 1,
		minAmount: 0.1,
	},
	{
		id: '14',
		name: 'Esencia de vainilla',
		price: 180,
		unit: 'litro',
		amount: 1,
		minAmount: 0.01,
	},
	{ id: '15', name: 'Sal', price: 8, unit: 'kg', amount: 1, minAmount: 0.005 },
];

export const products: Product[] = [
	{
		id: 1,
		name: 'Roll Clásico Risueño',
		price: 50,
		image: '/img/classic-cinnamon-roll-with-icing.png',
		description:
			'Nuestro rollo de canela emblemático que te hará reír de alegría',
		rating: 5,
		available: true,
		recipe: {
			id: '1',
			name: 'Roll Clásico Risueño',
			batchSize: 12,
			sellingPrice: 50,
			profitMargin: 60,
			available: true,
			ingredients: [
				{ ingredientId: '1', amount: 1 },
				{ ingredientId: '2', amount: 0.3 },
				{ ingredientId: '3', amount: 0.25 },
				{ ingredientId: '4', amount: 0.05 },
				{ ingredientId: '5', amount: 0.05 },
				{ ingredientId: '6', amount: 0.5 },
				{ ingredientId: '7', amount: 0.5 },
				{ ingredientId: '8', amount: 0.2 },
				{ ingredientId: '14', amount: 0.02 },
				{ ingredientId: '15', amount: 0.01 },
			],
			steps: [
				'Mezclar harina, azúcar, levadura y sal en un bowl grande',
				'Agregar mantequilla derretida y huevos batidos',
				'Incorporar leche tibia poco a poco mientras se amasa',
				'Amasar por 10 minutos hasta obtener una masa suave',
				'Dejar reposar en lugar tibio por 1 hora hasta que duplique su tamaño',
				'Extender la masa en rectángulo de 40x30 cm',
				'Espolvorear canela y azúcar uniformemente',
				'Enrollar firmemente desde el lado largo',
				'Cortar en 12 porciones iguales',
				'Colocar en molde engrasado y dejar reposar 30 minutos',
				'Hornear a 180°C por 25-30 minutos hasta dorar',
				'Dejar enfriar y decorar con glaseado de crema',
			],
		},
	},
	{
		id: 2,
		name: 'Roll de Choco Risas',
		price: 65,
		image: '/img/chocolate-cinnamon-roll-with-chocolate-drizzle.png',
		description: 'Doble chocolate delicioso que es seriamente divertido',
		rating: 5,
		available: false,
		recipe: {
			id: '2',
			name: 'Roll de Choco Risas',
			batchSize: 12,
			sellingPrice: 65,
			profitMargin: 65,
			available: true,
			ingredients: [
				{ ingredientId: '1', amount: 1 },
				{ ingredientId: '2', amount: 0.4 },
				{ ingredientId: '3', amount: 0.3 },
				{ ingredientId: '9', amount: 0.3 },
				{ ingredientId: '5', amount: 0.05 },
				{ ingredientId: '6', amount: 0.5 },
				{ ingredientId: '7', amount: 0.5 },
				{ ingredientId: '14', amount: 0.02 },
				{ ingredientId: '15', amount: 0.01 },
			],
			steps: [
				'Mezclar harina, cacao en polvo, azúcar y levadura',
				'Agregar mantequilla, huevos y esencia de vainilla',
				'Incorporar leche tibia gradualmente mientras se amasa',
				'Amasar hasta obtener consistencia elástica',
				'Reposar 1 hora en lugar tibio cubierto',
				'Extender masa y esparcir chips de chocolate',
				'Enrollar cuidadosamente y cortar en 12 porciones',
				'Colocar en molde y reposar 30 minutos más',
				'Hornear a 175°C por 30-35 minutos',
				'Preparar salsa de chocolate para bañar',
				'Decorar con chocolate derretido y chips',
			],
		},
	},
	{
		id: 3,
		name: 'Remolino de Fresa',
		price: 60,
		image: '/img/strawberry-cinnamon-roll-with-pink-icing.png',
		description: 'Giro dulce de fresa que te hará sonreír',
		rating: 4.8,
		available: true,
		recipe: {
			id: '3',
			name: 'Remolino de Fresa',
			batchSize: 12,
			sellingPrice: 60,
			profitMargin: 62,
			available: true,
			ingredients: [
				{ ingredientId: '1', amount: 1 },
				{ ingredientId: '2', amount: 0.35 },
				{ ingredientId: '3', amount: 0.25 },
				{ ingredientId: '10', amount: 0.4 },
				{ ingredientId: '5', amount: 0.05 },
				{ ingredientId: '6', amount: 0.5 },
				{ ingredientId: '7', amount: 0.5 },
				{ ingredientId: '13', amount: 0.15 },
				{ ingredientId: '14', amount: 0.02 },
			],
			steps: [
				'Preparar puré de fresas frescas',
				'Mezclar harina, azúcar y levadura',
				'Incorporar puré de fresa, mantequilla y huevos',
				'Amasar hasta que la masa no se pegue',
				'Dejar levar por 1 hora en lugar cálido',
				'Extender masa y esparcir mermelada de fresa',
				'Enrollar firmemente y cortar en porciones',
				'Disponer en molde y reposar 25 minutos',
				'Hornear a 180°C por 25 minutos',
				'Preparar glaseado rosa con queso crema',
				'Decorar con fresas frescas en rodajas',
			],
		},
	},
	{
		id: 4,
		name: 'Arándano en Verano',
		price: 65,
		image: '/img/blueberry-cinnamon-roll-with-cream-cheese-icing.png',
		description: 'Repleto de arándanos y risas',
		rating: 4.9,
		available: false,
		recipe: {
			id: '4',
			name: 'Arándano en Verano',
			batchSize: 12,
			sellingPrice: 65,
			profitMargin: 63,
			available: true,
			ingredients: [
				{ ingredientId: '1', amount: 1 },
				{ ingredientId: '2', amount: 0.35 },
				{ ingredientId: '3', amount: 0.25 },
				{ ingredientId: '11', amount: 0.35 },
				{ ingredientId: '5', amount: 0.05 },
				{ ingredientId: '6', amount: 0.5 },
				{ ingredientId: '7', amount: 0.5 },
				{ ingredientId: '13', amount: 0.2 },
				{ ingredientId: '14', amount: 0.02 },
				{ ingredientId: '4', amount: 0.03 },
			],
			steps: [
				'Mezclar harina, azúcar, levadura y canela',
				'Agregar mantequilla, huevos y leche tibia',
				'Amasar hasta obtener masa homogénea',
				'Dejar reposar 1 hora hasta que doble tamaño',
				'Extender masa y distribuir arándanos frescos',
				'Espolvorear azúcar morena y canela',
				'Enrollar cuidadosamente para no aplastar frutas',
				'Cortar en 12 rollos y colocar en molde',
				'Reposar 30 minutos hasta que esponjen',
				'Hornear a 175°C por 28-32 minutos',
				'Preparar glaseado de queso crema con esencia de vainilla',
				'Decorar con arándanos frescos y glaseado',
			],
		},
	},
	{
		id: 5,
		name: 'Glaseado Divertido',
		price: 45,
		image: '/img/glazed-cinnamon-roll-with-sugar-glaze.png',
		description: 'Simple, dulce y garantizado para hacerte reír',
		rating: 4.7,
		available: true,
		recipe: {
			id: '5',
			name: 'Glaseado Divertido',
			batchSize: 12,
			sellingPrice: 45,
			profitMargin: 55,
			available: true,
			ingredients: [
				{ ingredientId: '1', amount: 1 },
				{ ingredientId: '2', amount: 0.4 },
				{ ingredientId: '3', amount: 0.2 },
				{ ingredientId: '4', amount: 0.04 },
				{ ingredientId: '5', amount: 0.05 },
				{ ingredientId: '6', amount: 0.4 },
				{ ingredientId: '7', amount: 0.45 },
				{ ingredientId: '8', amount: 0.25 },
				{ ingredientId: '14', amount: 0.015 },
			],
			steps: [
				'Combinar harina, azúcar, levadura y sal',
				'Incorporar mantequilla ablandada y huevos',
				'Añadir leche tibia gradualmente mientras se mezcla',
				'Amasar por 8-10 minutos hasta suavidad',
				'Dejar levar 45 minutos en lugar tibio',
				'Extender masa en rectángulo uniforme',
				'Esparcir mezcla de canela y azúcar',
				'Enrollar firmemente y cortar en 12 piezas',
				'Colocar en molde y reposar 20 minutos',
				'Hornear a 180°C por 20-25 minutos',
				'Preparar glaseado simple con azúcar glass y leche',
				'Bañar los rollos calientes con glaseado generosamente',
			],
		},
	},
	{
		id: 6,
		name: 'Caramelo Crujiente',
		price: 70,
		image: '/img/caramel-cinnamon-roll-with-crunchy-topping.png',
		description: 'Delicioso caramelo crujiente que te hará reír a carcajadas',
		rating: 5,
		available: false,
		recipe: {
			id: '6',
			name: 'Caramelo Crujiente',
			batchSize: 12,
			sellingPrice: 70,
			profitMargin: 68,
			available: true,
			ingredients: [
				{ ingredientId: '1', amount: 1 },
				{ ingredientId: '2', amount: 0.35 },
				{ ingredientId: '3', amount: 0.3 },
				{ ingredientId: '12', amount: 0.25 },
				{ ingredientId: '4', amount: 0.04 },
				{ ingredientId: '5', amount: 0.05 },
				{ ingredientId: '6', amount: 0.5 },
				{ ingredientId: '7', amount: 0.5 },
				{ ingredientId: '13', amount: 0.18 },
				{ ingredientId: '14', amount: 0.02 },
			],
			steps: [
				'Preparar base con harina, azúcar y levadura',
				'Agregar mantequilla, huevos y leche',
				'Amasar hasta lograr textura sedosa',
				'Dejar reposar 1 hora hasta que leve',
				'Extender masa y esparcir caramelo suave',
				'Agregar nueces picadas para crujiente (opcional)',
				'Enrollar cuidadosamente y cortar en porciones',
				'Colocar en molde con base de caramelo',
				'Dejar reposar 25 minutos hasta esponjar',
				'Hornear a 170°C por 30-35 minutos',
				'Dejar enfriar 5 minutos antes de desmoldar',
				'Decorar con salsa de caramelo y nueces caramelizadas',
			],
		},
	},
];

export const defaultTools: Tool[] = [
	// UTILITIES
	{
		id: 'util-1',
		name: 'Horno ',
		type: 'utility',
		category: 'energy',
		cost: 15,
		description: 'Consumo eléctrico por horneado (180°C por 25-30 min)',
	},
	{
		id: 'util-2',
		name: 'Estufa',
		type: 'utility',
		category: 'energy',
		cost: 5,
		description: 'Consumo de gas para preparaciones en estufa',
	},
	{
		id: 'util-3',
		name: 'Mezcladora',
		type: 'utility',
		category: 'equipment',
		cost: 8,
		description: 'Consumo eléctrico por batch de masa',
	},
	{
		id: 'util-4',
		name: 'Refrigeración',
		type: 'utility',
		category: 'energy',
		cost: 3,
		description: 'Costo de refrigeración para ingredientes',
	},

	// UTENSILS
	{
		id: 'uten-1',
		name: 'Juego de Medidores',
		type: 'utensil',
		category: 'measuring',
		description: 'Tazas y cucharas medidoras para ingredientes',
	},
	{
		id: 'uten-2',
		name: 'Báscula Digital',
		type: 'utensil',
		category: 'measuring',
		description: 'Para mediciones precisas en gramos',
	},
	{
		id: 'uten-3',
		name: 'Bowls Mezcladores',
		type: 'utensil',
		category: 'mixing',
		description: 'Set de bowls de diferentes tamaños',
	},
	{
		id: 'uten-4',
		name: 'Batidor de Alambre',
		type: 'utensil',
		category: 'mixing',
		description: 'Para incorporar aire en mezclas',
	},
	{
		id: 'uten-5',
		name: 'Espátula de Goma',
		type: 'utensil',
		category: 'mixing',
		description: 'Para raspar bowls y mezclar suavemente',
	},
	{
		id: 'uten-6',
		name: 'Rodillo para Masa',
		type: 'utensil',
		category: 'shaping',
		description: 'Para extender masa uniformemente',
	},
	{
		id: 'uten-7',
		name: 'Moldes para Hornear',
		type: 'utensil',
		category: 'baking',
		description: 'Charolas para hornear rolls',
	},
	{
		id: 'uten-8',
		name: 'Cuchillo de Sierra',
		type: 'utensil',
		category: 'cutting',
		description: 'Para cortar rolls sin aplastar',
	},
	{
		id: 'uten-9',
		name: 'Termómetro Digital',
		type: 'utensil',
		category: 'measuring',
		description: 'Para temperatura interna perfecta',
	},

	// ENHANCERS
	{
		id: 'enh-1',
		name: 'Mezcladora Planetaria',
		type: 'enhancer',
		category: 'equipment',
		cost: 25,
		description: 'Mezclado profesional para consistencia perfecta',
	},
	{
		id: 'enh-2',
		name: 'Proveedora de Masa',
		type: 'enhancer',
		category: 'equipment',
		cost: 12,
		description: 'Control de temperatura para fermentación óptima',
	},
	{
		id: 'enh-3',
		name: 'Soplete Culinario',
		type: 'enhancer',
		category: 'finishing',
		cost: 8,
		description: 'Para acabados caramelizados y decoraciones',
	},
	{
		id: 'enh-4',
		name: 'Manga Pastelera',
		type: 'enhancer',
		category: 'decorating',
		description: 'Para decoraciones precisas con glaseados',
	},
	{
		id: 'enh-5',
		name: 'Kit de Medición Avanzado',
		type: 'enhancer',
		category: 'measuring',
		cost: 15,
		description: 'Medidores de precisión para profesionales',
	},
];

export const toolCategories = {
	utility: [
		{ value: 'energy', label: 'Energía' },
		{ value: 'equipment', label: 'Equipo Eléctrico' },
	],
	utensil: [
		{ value: 'measuring', label: 'Medición' },
		{ value: 'mixing', label: 'Mezclado' },
		{ value: 'shaping', label: 'Formado' },
		{ value: 'baking', label: 'Horneado' },
		{ value: 'cutting', label: 'Corte' },
	],
	enhancer: [
		{ value: 'equipment', label: 'Equipo Profesional' },
		{ value: 'finishing', label: 'Acabados' },
		{ value: 'decorating', label: 'Decoración' },
		{ value: 'measuring', label: 'Precisión' },
	],
};
